from django.urls import path
from .views import index

urlpatterns = [
    path('', index),
    path('erro', index),
    path('not-found', index),
    path('biologia/frente-a', index),
    path('biologia/frente-b', index),
    path('biologia/frente-c', index),
    path('biologia/frente-d', index),
    path('biologia/frente-e', index),
    path('fisica/frente-a', index),
    path('fisica/frente-b', index),
    path('fisica/frente-c', index),
    path('fisica/frente-d', index),
    path('geografia/frente-a', index),
    path('geografia/frente-b', index),
    path('historia/frente-a', index),
    path('historia/frente-b', index),
    path('historia/frente-c', index),
    path('matematica/frente-a', index),
    path('matematica/frente-b', index),
    path('matematica/frente-c', index),
    path('matematica/frente-d', index),
    path('matematica/frente-e', index),
    path('portugues/frente-a', index),
    path('portugues/frente-b', index),
    path('portugues/frente-c', index),
    path('portugues/frente-d', index),
    path('quimica/frente-a', index),
    path('quimica/frente-b', index),
    path('quimica/frente-c', index),
    path('quimica/frente-d', index),
    path('quimica/frente-e', index),
    path('fisica', index),
    path('geografia', index),
    path('historia', index),
    path('matematica', index),
    path('portugues', index),
    path('quimica', index)
]