# Generated by Django 5.0.2 on 2024-02-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('materia', models.CharField(max_length=15)),
                ('frente', models.CharField(max_length=1)),
                ('numero', models.IntegerField(null=True)),
                ('criador', models.CharField(max_length=15, null=True)),
                ('enunciado', models.TextField()),
                ('visualizada', models.DateTimeField(auto_now_add=True)),
                ('concluida', models.BooleanField(default=0)),
                ('conclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
