# Generated by Django 5.0.2 on 2024-02-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questoes',
            name='alt_a',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='questoes',
            name='alt_b',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='questoes',
            name='alt_c',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='questoes',
            name='alt_correta',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='questoes',
            name='alt_d',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='questoes',
            name='alt_e',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
