# Generated by Django 5.0.2 on 2024-02-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_questoes_alt_a_questoes_alt_b_questoes_alt_c_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questoes',
            old_name='conclusao',
            new_name='data_conclusao',
        ),
        migrations.RenameField(
            model_name='questoes',
            old_name='visualizada',
            new_name='data_visualizacao',
        ),
        migrations.AddField(
            model_name='questoes',
            name='acertou',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questoes',
            name='alt_f',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='questoes',
            name='alt_g',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='questoes',
            name='alternativa_usuario',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questoes',
            name='pontuacao',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='questoes',
            name='pontuacao_a',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questoes',
            name='pontuacao_b',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='questoes',
            name='pontuacao_c',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='questoes',
            name='pontuacao_d',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='questoes',
            name='pontuacao_e',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='questoes',
            name='pontuacao_f',
            field=models.IntegerField(default=32),
        ),
        migrations.AddField(
            model_name='questoes',
            name='pontuacao_g',
            field=models.IntegerField(default=64),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='alt_correta',
            field=models.CharField(default='A', max_length=20),
        ),
    ]
