# Generated by Django 5.0.2 on 2024-02-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_conclusao_questoes_data_conclusao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questoes',
            name='imagem',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
    ]
