# Generated by Django 5.0.2 on 2024-03-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_questoes_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='questoes',
            name='afirmativa_1',
            field=models.TextField(default='N/A', null=True),
        ),
        migrations.AddField(
            model_name='questoes',
            name='afirmativa_2',
            field=models.TextField(default='N/A', null=True),
        ),
        migrations.AddField(
            model_name='questoes',
            name='afirmativa_3',
            field=models.TextField(default='N/A', null=True),
        ),
        migrations.AddField(
            model_name='questoes',
            name='afirmativa_4',
            field=models.TextField(default='N/A', null=True),
        ),
        migrations.AddField(
            model_name='questoes',
            name='afirmativa_5',
            field=models.TextField(default='N/A', null=True),
        ),
    ]
