# Generated by Django 5.0.2 on 2024-03-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_questoes_afirmativa_1_questoes_afirmativa_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questoes',
            name='comando_enunciado',
            field=models.TextField(default='N/A', null=True),
        ),
    ]
