# Generated by Django 5.0.2 on 2024-03-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_questoes_comando_enunciado'),
    ]

    operations = [
        migrations.AddField(
            model_name='questoes',
            name='conta_pontuacao',
            field=models.BooleanField(default=0),
        ),
    ]
