# Generated by Django 5.0.2 on 2024-03-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_questoes_conta_pontuacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questoes',
            name='afirmativa_1',
        ),
        migrations.RemoveField(
            model_name='questoes',
            name='afirmativa_2',
        ),
        migrations.RemoveField(
            model_name='questoes',
            name='afirmativa_3',
        ),
        migrations.RemoveField(
            model_name='questoes',
            name='afirmativa_4',
        ),
        migrations.RemoveField(
            model_name='questoes',
            name='afirmativa_5',
        ),
        migrations.RemoveField(
            model_name='questoes',
            name='comando_enunciado',
        ),
    ]
