# Generated by Django 5.0.2 on 2024-03-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_questoes_afirmativa_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questoes',
            name='pontuacao_a',
        ),
        migrations.RemoveField(
            model_name='questoes',
            name='pontuacao_b',
        ),
        migrations.RemoveField(
            model_name='questoes',
            name='pontuacao_c',
        ),
        migrations.RemoveField(
            model_name='questoes',
            name='pontuacao_d',
        ),
        migrations.RemoveField(
            model_name='questoes',
            name='pontuacao_e',
        ),
        migrations.RemoveField(
            model_name='questoes',
            name='pontuacao_f',
        ),
        migrations.RemoveField(
            model_name='questoes',
            name='pontuacao_g',
        ),
        migrations.AddField(
            model_name='questoes',
            name='texto_a',
            field=models.TextField(default='Texto da alternativa A'),
        ),
        migrations.AddField(
            model_name='questoes',
            name='texto_b',
            field=models.TextField(default='Texto da alternativa B'),
        ),
        migrations.AddField(
            model_name='questoes',
            name='texto_c',
            field=models.TextField(default='Texto da alternativa C'),
        ),
        migrations.AddField(
            model_name='questoes',
            name='texto_d',
            field=models.TextField(default='Texto da alternativa D'),
        ),
        migrations.AddField(
            model_name='questoes',
            name='texto_e',
            field=models.TextField(default='Texto da alternativa E'),
        ),
        migrations.AddField(
            model_name='questoes',
            name='texto_f',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questoes',
            name='texto_g',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='alt_a',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='alt_b',
            field=models.CharField(default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='alt_c',
            field=models.CharField(default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='alt_d',
            field=models.CharField(default='D', max_length=2),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='alt_e',
            field=models.CharField(default='E', max_length=2),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='alt_f',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='alt_g',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='criador',
            field=models.CharField(default='Criador', max_length=15),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
