# Generated by Django 5.0.2 on 2024-03-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_questoes_pontuacao_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoes',
            name='alt_e',
            field=models.CharField(default='E', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='texto_e',
            field=models.TextField(default='Texto da alternativa E', null=True),
        ),
    ]
