# Generated by Django 5.0.2 on 2024-03-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_questoes_alt_e_alter_questoes_texto_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoes',
            name='alt_a',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='alt_b',
            field=models.CharField(default='2', max_length=2),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='alt_c',
            field=models.CharField(default='3', max_length=2),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='alt_d',
            field=models.CharField(default='4', max_length=2),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='alt_e',
            field=models.CharField(default='5', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='alt_f',
            field=models.CharField(default='6', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='alt_g',
            field=models.CharField(default='7', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='criador',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='texto_e',
            field=models.TextField(null=True),
        ),
    ]
