# Generated by Django 5.0.2 on 2024-03-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_questoes_alt_a_alter_questoes_alt_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoes',
            name='alt_correta',
            field=models.IntegerField(default=1),
        ),
    ]
