# Generated by Django 5.0.2 on 2024-03-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_questoes_alt_correta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoes',
            name='alt_correta',
            field=models.JSONField(default=list),
        ),
    ]
