# Generated by Django 5.0.2 on 2024-03-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_questoes_alt_correta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoes',
            name='conta_pontuacao',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
