# Generated by Django 5.0.2 on 2024-03-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_questoes_acertou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoes',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
